server:
  port: 8083
  
spring:
  application:
    name: API-GATEWAY
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    
  cloud:
    gateway:
      routes:
      - id : CITIZEN-SERVICE
        uri:
          lb://CITIZEN-SERVICE
        predicates:
        - Path=/citizen/**
        
      - id : VACCINATION-CENTRE-SERVICE
        uri:
          lb://VACCINATION-CENTRE-SERVICE
        predicates:
        - Path=/vaccinationcenter/**