server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CitizenDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  application:
    name: CITIZEN-SERVICE
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect